# Generated by Django 2.2.8 on 2019-12-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(help_text='visitor or host', max_length=7),
        ),
    ]
