# Generated by Django 2.2.8 on 2019-12-14 17:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191214_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='enter phone number', max_length=128, region=None),
        ),
    ]
