# Generated by Django 2.2.8 on 2019-12-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fk',
        ),
    ]
