# Generated by Django 2.2.8 on 2019-12-17 17:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191217_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 17, 39, 17, 959350, tzinfo=utc)),
        ),
    ]
