# Generated by Django 2.2.8 on 2019-12-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='confirm_password',
        ),
    ]
